inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - bin/*
    - db/schema.rb

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 160
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/**/**/*.rb'
    - 'spec/**/**/**/*.rb'

Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/Lambda:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
#Metrics/ParameterLists:
#  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Lint/SafeNavigationConsistency:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Naming/MethodParameterName:
  Exclude:
    - 'lib/**/*'
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/SpecFilePathSuffix:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/LetSetup:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Performance/Casecmp:
  Enabled: false
